code_submission/urls.py
"""
Copyright (c) 2016 Gabriel Esteban

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of
the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace='accounts')),
    url(r'^', include('problem.urls')),
    url(r'^', include('submission.urls')),
    url(r'^', include('main.urls')),
    url(r'^', include('review.urls'))
]

main/urls.py
"""
Copyright (c) 2016 Gabriel Esteban

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of
the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from main.views import HomeView, RankingProblemsView, RankingUsersView

urlpatterns = [
    url(r'^$', login_required(HomeView.as_view()), name='home'),
    url(r'^ranking/problems$', login_required(RankingProblemsView.as_view()), name='ranking_problems'),
    url(r'^ranking/users', login_required(RankingUsersView.as_view()), name='ranking_users')
]

submission/urls.py
"""
Copyright (c) 2016 Gabriel Esteban

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of
the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from submission.views import SubmitView, SubmissionDetail, SubmissionList

urlpatterns = [
    url(r'^problem/(?P<pk>\d+)/submit$', login_required(SubmitView.as_view()), name='submit'),
    url(r'^problem/(?P<pk>\d+)/submissions$', login_required(SubmissionList.as_view()), name='submissions'),
    url(r'^problem/(?P<pk>\d+)/submissions/(?P<pk_submission>\d+)$', login_required(SubmissionDetail.as_view()), name='submission'),
]

review/models.py
"""
Copyright (c) 2016 Gabriel Esteban

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of
the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

from __future__ import unicode_literals

from django.db import models

from submission.models import Submission
from ums.models import Judge


class Review(models.Model):
    submission = models.ForeignKey(Submission)
    reviewer = models.ForeignKey(Judge)
    comment = models.TextField()

submission/models.py
"""
Copyright (c) 2016 Gabriel Esteban

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of
the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

from __future__ import unicode_literals

import urlparse

from django.core.files.storage import FileSystemStorage
from django.db import models

from code_submission.settings import BASE_DIR
from problem.models import Problem
from ums.models import Student


class Submission(models.Model):
    problem = models.ForeignKey(Problem)
    submitter = models.ForeignKey(Student)
    code = models.URLField()
    STATUS_CHOICES = (
        (0, 'Not revised'),
        (1, 'Started revising'),
        (2, 'Revised and accepted'),
        (3, 'Revised and declined')
    )
    status = models.IntegerField(default=0, choices=STATUS_CHOICES)
    number = models.IntegerField(default=1)

    def __unicode__(self):
        return self.problem.__unicode__() + ' #' + str(self.number)

submission/forms.py
"""
Copyright (c) 2016 Gabriel Esteban

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of
the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

from django import forms

from submission.models import Submission


class SubmissionForm(forms.ModelForm):
    class Meta:
        model = Submission
        fields = ['code']

submission/views.py
"""
Copyright (c) 2016 Gabriel Esteban

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of
the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import redirect
from django.views.generic import TemplateView

from problem.models import Problem
from submission.forms import SubmissionForm
from submission.models import Submission
from ums.models import Student


class SubmitView(UserPassesTestMixin, TemplateView):
    template_name = "submission/submit.html"

    def test_func(self):
        return Student.objects.filter(user=self.request.user).count() != 0

    def get_context_data(self, **kwargs):
        context = super(SubmitView, self).get_context_data(**kwargs)

        context['problem'] = problem = Problem.objects.get(pk=kwargs.get('pk', None))
        context['submit_form'] = SubmissionForm()
        context['submissions'] = subs = Submission.objects.filter(problem=problem, submitter=self.request.user.student)
        context['can_submit'] = ([x for x in subs if x.status <= 1 or x.status == 2].__len__() == 0)

        return context

    def post(self, request, *args, **kwargs):
        problem = Problem.objects.get(pk=kwargs.get('pk', None))
        form = SubmissionForm(request.POST, request.FILES)

        if form.is_valid():
            submission = Submission(problem=problem, submitter=request.user.student, code=request.POST['code'],
                                    number=Submission.objects.filter(problem=problem,
                                                                     submitter=request.user.student).count()+1
                                    )
            submission.save()

            return redirect('submission', problem.pk, submission.pk)
        else:
            return redirect('submit', problem.pk)


class SubmissionDetail(UserPassesTestMixin, TemplateView):
    template_name = "submission/submission_detail.html"

    def test_func(self):
        return Student.objects.filter(user=self.request.user).count() != 0 and self.request.user == Submission.objects.get(pk=self.kwargs.get('pk_submission', None)).submitter.user

    def get_context_data(self, **kwargs):
        context = super(SubmissionDetail, self).get_context_data(**kwargs)

        context['submission'] = Submission.objects.get(pk=kwargs.get('pk_submission', None))

        return context


class SubmissionList(UserPassesTestMixin, TemplateView):
    template_name = "submission/submission_list.html"

    def test_func(self):
        return Student.objects.filter(user=self.request.user).count() != 0

    def get_context_data(self, **kwargs):
        context = super(SubmissionList, self).get_context_data(**kwargs)

        context['problem'] = problem = Problem.objects.get(pk=kwargs.get('pk', None))
        context['submissions'] = Submission.objects.filter(submitter=self.request.user.student, problem=problem)

        return context

templates/submission/submission_detail.html
{% extends "base_site.html" %}
{% load i18n static %}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href="{% static "css/font-awesome.min.css" %}"/>
{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'home' %}">{% trans 'Home' %}</a>
        &rsaquo; <a href="{% url 'problems' %}">{% trans 'Problems' %}</a>
        &rsaquo; <a href="{% url 'problem' submission.problem.pk %}">{{ submission.problem.title }}</a>
        &rsaquo; <a href="{% url 'submissions' submission.problem.pk %}">{% trans 'Submissions' %}</a>
        &rsaquo; {{ submission }}
    </div>
{% endblock %}

{% block site_title %}{{ submission.problem.title}}{% endblock %}

{% block content %}
    <h1>{{ submission }}</h1>
    <a class="button margin-bottom-m" href="{{ submission.code }}">{% trans "Download code" %}</a>
    <h1>{% trans 'Review' %}</h1>
    {% if submission.review_set.all %}
        <p>{% trans 'Status' %}: {% if submission.status == 2 %}<i class="fa fa-check-circle margin-right-xs" style="color: green;"></i>{% elif submission.status == 3 %}<i class="fa fa-times-circle margin-right-xs" style="color: red;"></i>{% else %}<i class="fa fa-circle margin-right-xs" style="color: lightgray;"></i>{% endif %}</p>
        <div class="row">
            {% for review in submission.review_set.all %}
                <div class="col-md-12">
                    <h3>{{ review.reviewer }}</h3>
                    <div class="text">
                        {{ review.comment }}
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="text">{% trans "This submission hasn't been revised yet" %}</div>
    {% endif %}
{% endblock %}

templates/submission/submission_list.html
{% extends "base_site.html" %}
{% load i18n static %}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href="{% static "css/font-awesome.min.css" %}"/>
{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'home' %}">{% trans 'Home' %}</a>
        &rsaquo; <a href="{% url 'problems' %}">{% trans 'Problems' %}</a>
        &rsaquo; <a href="{% url 'problem' problem.pk %}">{{ problem.title }}</a>
        &rsaquo; {% trans 'Submissions' %}
    </div>
{% endblock %}

{% block site_title %}{% trans 'Submissions' %}: {{ problem.title}}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>{% trans 'Submissions' %}</h1>
            <ol>
                {% for submission in submissions %}
                    <li>
                        {% if submission.status == 2 %}<i class="fa fa-check-circle margin-right-xs" style="color: green;"></i>{% elif submission.status == 3 %}<i class="fa fa-times-circle margin-right-xs" style="color: red;"></i>{% else %}<i class="fa fa-circle margin-right-xs" style="color: lightgray;"></i>{% endif %}
                        <a href="{% url 'submission' submission.problem.pk submission.pk %}">{{ submission }}</a>
                    </li>
                {% empty %}
                    <p>{% trans "There's nothing submitted." %}</p>
                {% endfor %}
            </ol>
        </div>
    </div>
{% endblock %}

templates/submission/submit.html
{% extends "base_site.html" %}
{% load i18n static %}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href="{% static "css/font-awesome.min.css" %}"/>
{% endblock %}

{% block site_title %}{{ problem.title }}{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'home' %}">{% trans 'Home' %}</a>
        &rsaquo; <a href="{% url 'problems' %}">{% trans 'Problems' %}</a>
        &rsaquo; <a href="{% url 'problem' problem.pk %}">{{ problem.title }}</a>
        &rsaquo; {% trans "Submit" %}
    </div>
{% endblock %}

{% block content %}
    <h1>{% trans 'Submit' %}: {{ problem.title }}</h1>
    <div class="row">
        <div class="col-md-6">
            {% if can_submit %}
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12">
                            {{ submit_form.code }}
                        </div>
                        <div class="col-md-12">
                            <input type="submit" class="margin-top-m" value="{% trans 'Submit' %}">
                        </div>
                    </div>
                </form>
            {% else %}
                <div class="alert alert-danger">{% trans "There's a submission on the waitlist or there's a submission already aproved for this problem." %}</div>            {% endif %}
        </div>
        <div class="col-md-6">
            <h1>{% trans 'Submissions' %}</h1>
            <ol>
                {% for submission in submissions %}
                    <li>
                        {% if submission.status == 2 %}<i class="fa fa-check-circle margin-right-xs" style="color: green;"></i>{% elif submission.status == 3 %}<i class="fa fa-times-circle margin-right-xs" style="color: red;"></i>{% else %}<i class="fa fa-circle margin-right-xs" style="color: lightgray;"></i>{% endif %}
                        <a href="{% url 'submission' submission.problem.pk submission.pk %}">{{ submission }}</a>
                    </li>
                {% empty %}
                    <p>{% trans "There's nothing submitted." %}</p>
                {% endfor %}
            </ol>
        </div>
    </div>
{% endblock %}